name: "easy_ride_devcontainer"

services:
  mongodb:
    image: mongo:latest
    container_name: easy_ride_mongodb
    ports:
      - "9001:27017"
    volumes:
      - ../docker-data/mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: easy_ride
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
    secrets:
      - mongodb_root_password
      - mongodb_root_username
    restart: always

secrets:
  mongodb_root_password:
    file: ../secrets/mongodb_root_password
  mongodb_root_username:
    file: ../secrets/mongodb_root_username
